import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { ROUTE_LENGTH_VH, SCENE_IDS, VW_PER_VH, screenDistance } from "@/lib/spatial/scenes";
import {
  BREAK_CUT,
  EXIT_FROM,
  averageCameraSpeed,
  exitGeometry,
  routeLegs,
  sceneFocusProgress,
} from "@/lib/spatial/sceneRoute";

// V14 — THE ROUTE-FOCUS DUMP, AS A TOOL RATHER THAN A HAND-EDITED FILE.
//
// Every browser probe under tests/tools reads a scene's focal progress from a
// committed `route-focus.json`. Those files were regenerated by hand whenever
// the route moved, and the v8 and v13 copies already disagree with each other
// (the V11 step change moved every focus). This writes the dump from the route
// module itself, so an artifact can never describe a route the camera does not
// run.
//
// Only WRITES when `ROUTE_FOCUS_OUT` names a file; otherwise it asserts the
// derived numbers are sane and exits. Run:
//
//   ROUTE_FOCUS_OUT=docs/review/v14-owner-visual/metrics/route-focus.json pnpm vitest run tests/unit/route-focus-dump.test.ts
//
// The dump also carries the world's ARC LENGTH per route, which is what the
// V14 scroll-gearing derivation reads (lib/spatial/cameraFilter.ts,
// PAGE_GEARING): total screen units of camera travel, sampled along the real
// curve rather than between anchors.

function legLength(points: { x: number; y: number }[]): number {
  let total = 0;
  for (let i = 1; i < points.length; i += 1) total += screenDistance(points[i - 1]!, points[i]!);
  return total;
}

function dump(mobile: boolean) {
  const legs = routeLegs(mobile, 64);
  const routeOne = legs.filter((leg) => leg.route === 1);
  const routeTwo = legs.filter((leg) => leg.route === 2);
  const focus = Object.fromEntries(SCENE_IDS.map((id) => [id, sceneFocusProgress(id, mobile)]));
  return {
    focus,
    worldLength: {
      one: +routeOne.reduce((sum, leg) => sum + legLength(leg.points), 0).toFixed(2),
      two: +routeTwo.reduce((sum, leg) => sum + legLength(leg.points), 0).toFixed(2),
      total: +legs.reduce((sum, leg) => sum + legLength(leg.points), 0).toFixed(2),
    },
    averageCameraSpeed: +averageCameraSpeed(mobile).toFixed(2),
  };
}

describe("route focus dump", () => {
  it("derives every focal progress from the route, in order, in both modes", () => {
    const desktop = dump(false);
    const mobile = dump(true);
    for (const table of [desktop.focus, mobile.focus]) {
      let previous = -1;
      for (const id of SCENE_IDS) {
        expect(table[id]).toBeGreaterThan(previous);
        previous = table[id]!;
      }
    }
    expect(desktop.worldLength.total).toBeGreaterThan(0);
    expect(mobile.worldLength.total).toBeGreaterThan(0);

    const out = process.env.ROUTE_FOCUS_OUT;
    if (!out) return;
    const exit = exitGeometry();
    const payload = {
      generatedBy: "tests/unit/route-focus-dump.test.ts",
      ROUTE_LENGTH_VH,
      BREAK_CUT,
      EXIT_FROM,
      VW_PER_VH,
      exit: exit.turn,
      desktop: desktop.focus,
      mobile: mobile.focus,
      worldLength: { desktop: desktop.worldLength, mobile: mobile.worldLength },
      averageCameraSpeed: {
        desktop: desktop.averageCameraSpeed,
        mobile: mobile.averageCameraSpeed,
      },
    };
    mkdirSync(path.dirname(out), { recursive: true });
    writeFileSync(out, JSON.stringify(payload, null, 2) + "\n");
  });
});
